apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/tconuorah/awsdev-app-deploy_w-gitops
    targetRevision: gitops
    path: helm/aws-dev
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: aws-dev
    

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
